### ISSUE TITLE
ec-gpu-gen 0.2.1 fails to build on docs.rs due to missing `nvcc`

### ISSUE THREAD

**Issue by johnchandlerburnham** [filecoin-project/ec-gpu#19]
https://docs.rs/crate/ec-gpu-gen/0.2.1/builds/531107

I have nix-based fix which adds the `cudatoolkit` dependency to fix this: https://github.com/lurk-lang/ec-gpu/blob/df6de7cd06e37ce3ba8d311e5d6c073a6e87b15a/flake.nix#L51, but presumably there's a non-nix way to get the docs.rs CI to include this.

**Comment by johnchandlerburnham** [comment]
I opened a WIP PR for this here: https://github.com/filecoin-project/ec-gpu/pull/20.

I notice that we don't have CI enabled for this repo, although we do have a `.circleci` config

**Comment by vmx** [comment]
Thanks @johnchandlerburnham, I think I found a non-nix based solution to the problem at https://github.com/filecoin-project/ec-gpu/pull/21.
