### ISSUE TITLE
some questions about principle of "FFT"

### ISSUE THREAD

**Issue by huapengcheng** [filecoin-project/ec-gpu#35]
I want some papers or blogs about the principles of "FFT" which used in "/ec-gpu/ec-gpu-gen/src/fft_cpu.rs/parallel_fft()".

**Comment by vmx** [comment]
This code comes originally from https://github.com/zkcrypto/bellman/blob/3c44bfe15358ae686f9e3780aaa4cbef8ec4a472/src/domain.rs#L316-L372 and was just ported over to this library, so we are not the authors of it.

**Comment by huapengcheng** [comment]
Thank you for your reply.
