### ISSUE TITLE
How to use methods in "G1Affine" by the <G as PrimeCurveAffine>::Curve?

### ISSUE THREAD

**Issue by huapengcheng** [filecoin-project/ec-gpu#36]
I want to transform the result of the function "multiexp" in gpu from the form of "<G as PrimeCurveAffine>::Curve" to "&[u8]".I want to use function "[to_uncompressed](https://docs.rs/blstrs/latest/blstrs/struct.G1Projective.html#method.to_uncompressed)" and "[from_uncompressed](https://docs.rs/blstrs/latest/blstrs/struct.G1Projective.html#method.from_uncompressed)".But these methods are in "G1Projective" and I can not use them in a  "<G as PrimeCurveAffine>::Curve" .
Please help me with this!
![image](https://user-images.githubusercontent.com/88694422/197766420-61df9401-3bc0-4fff-8350-2b56ec550b18.png)

**Comment by vmx** [comment]
It seems like you'd need to create your own helper functions that transform a Curve into bytes.
