### ISSUE TITLE
Questions about "POINT_multiexp" KERNEL in "cuda" code.

### ISSUE THREAD

**Issue by 20171759** [filecoin-project/ec-gpu#38]
in the code for "cuda", I noticed that you used an optimization in the "POINT_multiexp" KERNEL as shown below

      // O_o, weird optimization, having a single special case makes it
      // tremendously faster!
      // 511 is chosen because it's half of the maximum bucket len, but
      // any other number works... Bigger indices seems to be better...
        if(ind == 511) buckets[510] = G1_add_mixed(buckets[510], bases[i]);
        else if(ind--) buckets[ind] = G1_add_mixed(buckets[ind], bases[i]);

but when I remove the else branch, it becomes as shown below,

         if(ind--) buckets[ind] = G1_add_mixed(buckets[ind], bases[i]);

After testing on "RTX 3060", when the input scale is "2 ^ 21" and the input point is "G2Affine"，Your optimization has obvious effect. When the input scale is "2 ^ 21" and the input point is of "G1Affine" type ，Your optimization has no effect, but will lead to long execution time.
  Could you tell us in detail the role of optimization here?

**Comment by keyvank** [comment]
I researched why this is happening for a long time, I couldn’t figure it out. I guess it’s just magic :)

**Comment by 20171759** [comment]
Can you tell me the function of optimization here?

**Comment by 20171759** [comment]
> 
Can you tell me the function of optimization here

**Comment by 20171759** [comment]
> I researched why this is happening for a long time, I couldn’t figure it out. I guess it’s just magic :)

Can you tell me the role of optimization here? Is it the optimization of storage access?
