### ISSUE TITLE
Does it work with compute capability 5.2?

### ISSUE THREAD

**Issue by jayavanth** [filecoin-project/ec-gpu#51]
Hi, I'm trying to run the tests on my GPU. Wanted to know if it can run on GTX Titan X (Maxwell, 2015). When I run `cargo test` I get the following output

https://pastebin.com/ETDPm1d5

**Comment by jayavanth** [comment]
I was able to run an example from `rust-gpu-tools` so I guess that's not the issue

**Comment by vmx** [comment]
RUST_BACKTRACE=full EC_GPU_CUDA_NVCC_ARGS="--fatbin --gpu-architecture=sm_52 --generate-code=arch=compute_52,code=sm_52" cargo test

Worked for me. Though I'm on a RTX 3090ti.

**Comment by jayavanth** [comment]
Thank you! I think my mistake was that I didn't do a `cargo build` beforehand. I'm guessing that's the step when the kernels are generated. I'm quite new to Rust
