### ISSUE TITLE
Build failuer due to old rust toolchain configure

### ISSUE THREAD

**Issue by tie-pilot-qxw** [filecoin-project/ec-gpu#54]
When I tried to build the project, I got this:
error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.62.1
This can be fixed by changing the rustic version, but I'm not sure whether this will bring other potential problems.

**Comment by vmx** [comment]
Thanks for the bug report. I'll increase the Rust version, this shouldn't cause any issues. I thought it's a quick fix, but I just saw that the CI needs a bit of work. So it'll take a bit, but I'm on it.

**Comment by vmx** [comment]
Sorry for taking so long. I've now released `ec-gpu-gen` v0.7.1 which should fix the problem. If you have it as a dependency a `cargo update` should automatically pick it up.
